#Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
#Configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-blog-app-config
  namespace: dev
  labels:
    app: spring-boot-blog-app
data:
  dbURL: "jdbc:postgresql://postgres-db/blog"

---
#Secret
apiVersion: v1
kind: Secret
metadata:
  name: spring-boot-blog-app-secret
  namespace: dev
  labels:
    app: spring-boot-blog-app
data:
  dbUserName: cG9zdGdyZXM=
  dbPassword: cG9zdGdyZXM=

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-blog-app-deploy
  namespace: dev
  labels:
    app: spring-boot-blog-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-blog-app
  template:
    metadata:
      name: spring-boot-blog-app
      labels:
        app: spring-boot-blog-app
    spec:
      containers:
        - name: spring-boot-blog-app
          image: sarathvedha/spring-boot-blog-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  key: dbURL
                  name: spring-boot-blog-app-config
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: dbUserName
                  name: spring-boot-blog-app-secret
            - name: DB_PASSWD
              valueFrom:
                secretKeyRef:
                  key: dbPassword
                  name: spring-boot-blog-app-secret
          ports:
            - containerPort: 9090
      restartPolicy: Always

---
#Service
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-blog-app-service
  namespace: dev
  labels:
    app: spring-boot-blog-app
spec:
  selector:
    app: spring-boot-blog-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: LoadBalancer