apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-blog-app-deploy
  labels:
    app: spring-boot-blog-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-blog-app
  template:
    metadata:
      name: spring-boot-blog-app
      labels:
        app: spring-boot-blog-app
    spec:
      containers:
        - name: spring-boot-blog-app
          image: sarathvedha/springboot-blog-app:29
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  key: dbURL
                  name: spring-boot-blog-app-config
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: dbUserName
                  name: spring-boot-blog-app-secret
            - name: DB_PASSWD
              valueFrom:
                secretKeyRef:
                  key: dbPassword
                  name: spring-boot-blog-app-secret
          ports:
            - containerPort: 9090
      restartPolicy: Always
      
