apiVersion: v1
kind: Service
metadata:
  name: spring-boot-blog-app-service
  namespace: dev
spec:
  selector:
    app: spring-boot-blog-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: LoadBalancer
  
